#!/bin/bash
# Hook script for system-wide access to iftool.py


## TODO: tailor this to search for an appropriate version of Python
PYTHON=$(which python)


# Figure out where this script is running from
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
SCRIPT_DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"


# Run the iftool.py found next to script else try to import it from the standard location
IFTOOL=$SCRIPT_DIR/pmtatool.py
if [ -f "$IFTOOL" ]
then
    $PYTHON $IFTOOL "$@"
else
    $PYTHON -m iftool "$@"
fi
